#!/usr/bin/env python3

# -*- coding: utf-8 -*-
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

import click

import i18n_utils


"""
Tool for maintenance of .po and .pot files

Normally, the i18n-related files contain for each translatable string a
reference to all the source code locations where this string is found. This
meta data is useful for translators to assess how strings are used, but is not
relevant for normal development nor for running Kallithea. Such meta data, or
derived data like kallithea.pot, will inherently be outdated, and create
unnecessary churn and repository growth, making it harder to spot actual and
important changes.
"""

@click.group()
@click.option('--debug/--no-debug', default=False)
def cli(debug):
    if (debug):
        i18n_utils.do_debug = True
    pass

@cli.command()
@click.argument('po_files', nargs=-1)
def normalize_po_files(po_files):
    """Normalize the specified .po and .pot files.

    Only actual translations and essential headers will be preserved.
    """
    for po_file in po_files:
        i18n_utils._normalize_po_file(po_file, strip=True)

@cli.command()
@click.argument('file1')
@click.argument('file2')
def normalized_diff(file1, file2):
    """Compare two files while transparently normalizing them."""
    sys.exit(i18n_utils._normalized_diff(file1, file2, strip=True))

if __name__ == '__main__':
    cli()
